import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, useLocation, useNavigate } from 'react-router-dom';
import { AlertTriangle, ArrowRight, BarChart3, Bell, BriefcaseBusiness, CheckCircle2, ChevronRight, CircleDot, ClipboardCheck, Clock3, Download, FileText, Filter, Home, LogOut, Menu, Search, ShieldAlert, Sparkles, Users, X } from 'lucide-react';
import { jsPDF } from 'jspdf';
import './styles.css';

type Role = 'manager'|'team_lead'|'worker';
type Status = 'completed'|'in_progress'|'blocked'|'escalated'|'watch'|'open';
type Event = { id:string; source:'jira'|'incident'|'chat'|'commit'; record_id:string; timestamp:string; summary:string; status:Status; priority:'low'|'medium'|'high'|'critical'; worker_id:string; team_id:string; team_lead_id:string; update_type:string };
type User = { id:string; name:string; role:Role; title:string; team_id?:string; team_lead_id?:string };
type Team = { id:string; name:string; lead_id:string; worker_ids:string[] };
type HandoverItem = { source:string; record_id:string; timestamp:string; summary:string; priority:string; finalStatus:string; updates:string[] };
type Handover = { worker:User; team:Team; lead:User; shiftStart:string; shiftEnd:string; completed:HandoverItem[]; inProgress:HandoverItem[]; blockers:HandoverItem[]; watch:HandoverItem[]; priorities:HandoverItem[]; eventCount:number; duplicateUpdatesCollapsed:number; warnings:string[] };

const API = 'http://localhost:4000/api';
const demoUsers:User[] = [
 {id:'m1',name:'Rohan Mehta',role:'manager',title:'Operations Manager'},
 {id:'tl1',name:'Arun Kumar',role:'team_lead',title:'Team Lead',team_id:'t1'},
 {id:'tl2',name:'Meena Iyer',role:'team_lead',title:'Team Lead',team_id:'t2'},
 {id:'tl3',name:'Priya Shah',role:'team_lead',title:'Team Lead',team_id:'t3'},
 {id:'w1',name:'Karthik Rao',role:'worker',title:'Software Engineer',team_id:'t1',team_lead_id:'tl1'},
 {id:'w2',name:'Divya Nair',role:'worker',title:'QA Engineer',team_id:'t1',team_lead_id:'tl1'},
 {id:'w3',name:'Sanjay Menon',role:'worker',title:'Backend Engineer',team_id:'t1',team_lead_id:'tl1'},
 {id:'w4',name:'Priya Krishnan',role:'worker',title:'Frontend Engineer',team_id:'t1',team_lead_id:'tl1'},
 {id:'w5',name:'Ravi Kumar',role:'worker',title:'DevOps Engineer',team_id:'t2',team_lead_id:'tl2'},
 {id:'w6',name:'Harish Babu',role:'QA Engineer',team_id:'t2',team_lead_id:'tl2',title:'QA Engineer'},
 {id:'w7',name:'Nithya S',role:'Software Engineer',team_id:'t2',team_lead_id:'tl2',title:'Software Engineer'},
 {id:'w8',name:'Ajay Raj',role:'Software Engineer',team_id:'t3',team_lead_id:'tl3',title:'Software Engineer'},
 {id:'w9',name:'Deepa V',role:'Data Engineer',team_id:'t3',team_lead_id:'tl3',title:'Data Engineer'},
 {id:'w10',name:'Vignesh K',role:'Support Engineer',team_id:'t3',team_lead_id:'tl3',title:'Support Engineer'}
];
const teams:Team[] = [
 {id:'t1',name:'Team Alpha',lead_id:'tl1',worker_ids:['w1','w2','w3','w4']},
 {id:'t2',name:'Team Beta',lead_id:'tl2',worker_ids:['w5','w6','w7']},
 {id:'t3',name:'Team Gamma',lead_id:'tl3',worker_ids:['w8','w9','w10']}
];
const shiftStart = '2026-09-03T09:00:00+05:30'; const shiftEnd='2026-09-03T17:00:00+05:30'; const previousStart='2026-09-02T13:00:00+05:30'; const previousEnd='2026-09-02T21:00:00+05:30';

function fmt(iso:string){ return new Intl.DateTimeFormat('en-IN',{hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(iso)); }
function dateTime(iso:string){ return new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',hour12:true}).format(new Date(iso)); }
function getUser(id:string){return demoUsers.find(u=>u.id===id)!}
function getTeam(id:string){return teams.find(t=>t.id===id)!}

function App(){
 const [session,setSession]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem('shiftflow-session')||'null')}catch{return null}});
 const [selectedWorker,setSelectedWorker]=useState<string>(()=>localStorage.getItem('shiftflow-worker')||'w1');
 const [handover,setHandover]=useState<Handover|null>(null); const [modal,setModal]=useState<'summary'|'full'|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 useEffect(()=>{ if(session) localStorage.setItem('shiftflow-session',JSON.stringify(session)); else localStorage.removeItem('shiftflow-session') },[session]);
 useEffect(()=>{localStorage.setItem('shiftflow-worker',selectedWorker)},[selectedWorker]);
 const activeWorker = session?.role==='worker'?session.id:selectedWorker;
 const loadHandover=async(workerId=activeWorker)=>{ if(!workerId)return; setLoading(true);setError(''); try{const r=await fetch(`${API}/handover?workerId=${workerId}&start=${encodeURIComponent(shiftStart)}&end=${encodeURIComponent(shiftEnd)}`);if(!r.ok)throw new Error((await r.json()).error||'Unable to generate handover');setHandover(await r.json())}catch(e:any){setError(e.message||'Unable to generate handover')}finally{setLoading(false)}};
 useEffect(()=>{if(session) loadHandover(activeWorker)},[session,activeWorker]);
 if(!session) return <Login onLogin={setSession}/>;
 return <Shell user={session} onLogout={()=>setSession(null)} selectedWorker={activeWorker} setSelectedWorker={setSelectedWorker} handover={handover} loadHandover={loadHandover} loading={loading} error={error} setModal={setModal} modal={modal}/>;
}

function Login({onLogin}:{onLogin:(u:User)=>void}){const [role,setRole]=useState<Role>('manager');const [worker,setWorker]=useState('w1');return <div className="login-page"><div className="login-art"><div className="brand-mark"><Sparkles size={18}/> ShiftFlow</div><div className="login-copy"><span className="eyebrow">SHIFT INTELLIGENCE</span><h1>Every shift ends with clarity.</h1><p>Turn timestamped work activity into a traceable, deterministic handover for the next shift.</p><div className="proof"><CheckCircle2/><span>Grounded in source records, not invented summaries.</span></div></div></div><div className="login-panel"><div className="login-card"><div className="mobile-brand">ShiftFlow</div><h2>Sign in to your workspace</h2><p className="muted">Use a seeded demo account.</p><div className="role-switch">{(['manager','team_lead','worker'] as Role[]).map(r=><button key={r} className={role===r?'active':''} onClick={()=>setRole(r)}>{r==='team_lead'?'Team Lead':r[0].toUpperCase()+r.slice(1)}</button>)}</div>{role==='worker'&&<select value={worker} onChange={e=>setWorker(e.target.value)}>{demoUsers.filter(u=>u.role==='worker').map(u=><option key={u.id} value={u.id}>{u.name} — {getTeam(u.team_id!).name}</option>)}</select>}<button className="primary big" onClick={()=>onLogin(role==='manager'?demoUsers[0]:role==='team_lead'?demoUsers[1]:getUser(worker))}>Enter demo workspace <ArrowRight size={17}/></button><div className="login-note"><ShieldAlert size={15}/> Demo data only • no live Jira connection required</div></div></div></div>}

function Shell(p:{user:User,onLogout:()=>void,selectedWorker:string,setSelectedWorker:(s:string)=>void,handover:Handover|null,loadHandover:(id?:string)=>void,loading:boolean,error:string,setModal:(m:'summary'|'full'|null)=>void,modal:'summary'|'full'|null}){
 const [navOpen,setNavOpen]=useState(false); const [view,setView]=useState(p.user.role==='worker'?'my-shift':'dashboard');
 const allowed = p.user.role==='manager'?['dashboard','teams','team leads','workers','handover','reports']:p.user.role==='team_lead'?['dashboard','my team','workers','shift activity','handover']:['dashboard','my shift','my work','previous shift','next shift handover'];
 const team=p.user.team_id?getTeam(p.user.team_id):null; const workers=team?team.worker_ids.map(getUser):demoUsers.filter(u=>u.role==='worker');
 const openWorker=(id:string)=>{p.setSelectedWorker(id);setView(p.user.role==='worker'?'my shift':'worker');};
 return <div className="app"><aside className={navOpen?'open':''}><div className="sidebar-brand"><div className="logo"><Sparkles size={17}/></div><b>ShiftFlow</b></div><div className="workspace">OPERATIONS CONTROL</div><nav>{allowed.map(item=><button key={item} className={view===item?'nav-active':''} onClick={()=>{setView(item);setNavOpen(false)}}>{iconFor(item)}<span>{labelFor(item)}</span></button>)}</nav><div className="sidebar-bottom"><div className="session"><div className="avatar">{p.user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{p.user.name}</b><span>{labelFor(p.user.role)}</span></div></div><button className="logout" onClick={p.onLogout}><LogOut size={16}/> Sign out</button></div></aside><main><header><button className="menu" onClick={()=>setNavOpen(!navOpen)}><Menu/></button><div className="breadcrumbs"><span>Operations</span><ChevronRight size={14}/><b>{view==='worker'?getUser(p.selectedWorker).name:labelFor(view)}</b></div><div className="header-actions"><span className="live"><i/> Demo data synced</span><Bell size={18}/></div></header><div className="content">{view==='dashboard'&&<Dashboard user={p.user} onWorker={openWorker} onTeam={(id)=>{setView('team');p.setSelectedWorker(getTeam(id).worker_ids[0])}}/>}{view==='teams'&&<Teams onTeam={(id)=>{p.setSelectedWorker(getTeam(id).worker_ids[0]);setView('team')}}/>}{view==='team'&&team&&<TeamPage team={getTeam(getUser(p.selectedWorker).team_id!)} onWorker={openWorker}/>} {view==='team leads'&&<TeamLeads onWorker={openWorker}/>} {view==='workers'&&<Workers users={workers} onWorker={openWorker}/>} {view==='worker'||view==='my shift'||view==='my work'||view==='previous shift'||view==='shift activity'&&<WorkerPage userId={p.selectedWorker} session={p.user} handover={p.handover} onGenerate={()=>p.loadHandover(p.selectedWorker)} loading={p.loading} error={p.error} setModal={p.setModal}/>} {view==='handover'||view==='next shift handover'&&<HandoverPage handover={p.handover} loading={p.loading} error={p.error} onGenerate={()=>p.loadHandover(p.selectedWorker)} setModal={p.setModal}/>} {view==='reports'&&<Reports/>}</div></main>{p.modal&&p.handover&&<HandoverModal handover={p.handover} mode={p.modal} close={()=>p.setModal(null)}/>}</div>
}
function iconFor(v:string){const m:any={dashboard:<Home size={17}/>,teams:<Users size={17}/>, 'team leads':<Users size={17}/>,workers:<BriefcaseBusiness size={17}/>,handover:<FileText size={17}/>,reports:<BarChart3 size={17}/>, 'my team':<Users size={17}/>, 'shift activity':<Clock3 size={17}/>, 'my shift':<Clock3 size={17}/>, 'my work':<ClipboardCheck size={17}/>, 'previous shift':<ArrowRight size={17}/>, 'next shift handover':<FileText size={17}/>,worker:<Users size={17}/>,team:<Users size={17}/>}}; return m[v]||<CircleDot size={17}/>}
function labelFor(v:string){return v.split(' ').map(x=>x[0].toUpperCase()+x.slice(1)).join(' ')}

function Dashboard({user,onWorker,onTeam}:{user:User,onWorker:(id:string)=>void,onTeam:(id:string)=>void}){const stats=[['3','Teams'],['3','Team Leads'],['10','Workers'],['14','Active Tasks'],['21','Completed Today'],['6','Pending'],['2','Blockers']];return <><PageTitle title={user.role==='manager'?'Manager dashboard':'Team Alpha dashboard'} subtitle="Operational overview from seeded shift activity"/><div className="stats">{stats.map(([n,l])=><div className="stat" key={l}><span>{l}</span><strong>{n}</strong></div>)}</div><div className="section-head"><div><h2>Teams</h2><p className="muted">Click into the hierarchy to trace work down to a worker.</p></div><span className="source-pill">Source: shift activity</span></div><div className="team-grid">{teams.map(t=><div className="team-card" key={t.id} onClick={()=>onTeam(t.id)}><div className="team-top"><div className="team-icon">{t.name.split(' ')[1][0]}</div><span className="status-dot">Active</span></div><h3>{t.name}</h3><p>Team Lead: <b>{getUser(t.lead_id).name}</b></p><div className="team-metrics"><span>{t.worker_ids.length} workers</span><span>{t.id==='t1'?12:t.id==='t2'?9:5} active</span><span>{t.id==='t1'?3:t.id==='t2'?2:1} pending</span></div><div className="card-arrow">Open team <ChevronRight size={15}/></div></div>)}</div><div className="callout"><Sparkles size={18}/><div><b>Deterministic handovers</b><span>Timestamp filter → dedupe by source + record ID → final state → four sections → priorities.</span></div></div></>}
function PageTitle({title,subtitle,action}:{title:string,subtitle?:string,action?:React.ReactNode}){return <div className="page-title"><div><span className="eyebrow">WORKSPACE</span><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}
function Teams({onTeam}:{onTeam:(id:string)=>void}){return <><PageTitle title="Teams" subtitle="Manager view of all operational teams"/><div className="table-card"><table><thead><tr><th>Team</th><th>Team Lead</th><th>Workers</th><th>Active</th><th>Pending</th><th>Blockers</th><th/></tr></thead><tbody>{teams.map(t=><tr key={t.id} onClick={()=>onTeam(t.id)}><td><b>{t.name}</b></td><td>{getUser(t.lead_id).name}</td><td>{t.worker_ids.length}</td><td>{t.id==='t1'?12:t.id==='t2'?9:5}</td><td>{t.id==='t1'?3:t.id==='t2'?2:1}</td><td><span className={t.id==='t2'?'badge good':'badge bad'}>{t.id==='t2'?0:1}</span></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div></>}
function TeamLeads({onWorker}:{onWorker:(id:string)=>void}){return <><PageTitle title="Team Leads" subtitle="Assigned lead-to-team relationships"/><div className="people-grid">{teams.map(t=><div className="person-card" key={t.id}><div className="avatar large">{getUser(t.lead_id).name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h3>{getUser(t.lead_id).name}</h3><p>{getUser(t.lead_id).title} · {t.name}</p><div className="mini-list">{t.worker_ids.map(id=><button key={id} onClick={()=>onWorker(id)}>{getUser(id).name}<ChevronRight size={14}/></button>)}</div></div></div>)}</div></>}
function Workers({users,onWorker}:{users:User[],onWorker:(id:string)=>void}){return <><PageTitle title="Workers" subtitle="Browse worker profiles and shift traceability"/><div className="table-card"><div className="table-toolbar"><div className="search"><Search size={16}/><input placeholder="Search workers..."/></div><button className="secondary"><Filter size={15}/> Current shift</button></div><table><thead><tr><th>Worker</th><th>Team</th><th>Team Lead</th><th>Current task</th><th>Status</th><th/></tr></thead><tbody>{users.map(u=><tr key={u.id} onClick={()=>onWorker(u.id)}><td><div className="user-cell"><div className="avatar">{u.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{u.name}</b><small>{u.title}</small></div></div></td><td>{getTeam(u.team_id!).name}</td><td>{getUser(u.team_lead_id!).name}</td><td>{u.id==='w1'?'Payment API':u.id==='w3'?'Database connection':u.id==='w2'?'Login regression':'Service validation'}</td><td><span className={`badge ${u.id==='w3'?'bad':u.id==='w2'?'good':'info'}`}>{u.id==='w3'?'Blocked':u.id==='w2'?'Completed':'In Progress'}</span></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div></>}
function TeamPage({team,onWorker}:{team:Team,onWorker:(id:string)=>void}){return <><PageTitle title={team.name} subtitle={`Team Lead: ${getUser(team.lead_id).name} · ${team.worker_ids.length} workers`} action={<span className="status-pill"><i/> Active</span>}/><div className="stats compact"><div className="stat"><span>Workers</span><strong>{team.worker_ids.length}</strong></div><div className="stat"><span>Completed</span><strong>{team.id==='t1'?12:9}</strong></div><div className="stat"><span>In Progress</span><strong>{team.id==='t1'?4:3}</strong></div><div className="stat"><span>Blockers</span><strong>{team.id==='t2'?0:1}</strong></div></div><div className="table-card"><table><thead><tr><th>Worker</th><th>Current Task</th><th>Status</th><th>Last Shift</th><th>Current Shift</th><th/></tr></thead><tbody>{team.worker_ids.map(id=>{const u=getUser(id);return <tr key={id} onClick={()=>onWorker(id)}><td><b>{u.name}</b></td><td>{id==='w1'?'Payment API':id==='w2'?'Login module':id==='w3'?'Database connection':'Service validation'}</td><td><span className={`badge ${id==='w3'?'bad':id==='w2'?'good':'info'}`}>{id==='w3'?'Blocked':id==='w2'?'Completed':'In Progress'}</span></td><td>01 PM – 09 PM</td><td>09 AM – 05 PM</td><td><ChevronRight size={16}/></td></tr>})}</tbody></table></div></>}

function WorkerPage({userId,session,handover,onGenerate,loading,error,setModal}:{userId:string,session:User,handover:Handover|null,onGenerate:()=>void,loading:boolean,error:string,setModal:(m:'summary'|'full'|null)=>void}){const u=getUser(userId); const team=getTeam(u.team_id!); const [events,setEvents]=useState<Event[]>([]); useEffect(()=>{fetch(`${API}/events?workerId=${userId}`).then(r=>r.json()).then(setEvents).catch(()=>{})},[userId]); const current=events.filter(e=>e.timestamp>=shiftStart&&e.timestamp<=shiftEnd).sort((a,b)=>a.timestamp.localeCompare(b.timestamp)); return <><PageTitle title={u.name} subtitle="Worker profile · traceable shift activity" action={<button className="primary" onClick={onGenerate}><Sparkles size={15}/>{loading?'Generating…':'Generate handover'}</button>}/><div className="breadcrumbs local"><span>{session.role==='manager'?'Manager':team.name}</span><ChevronRight size={14}/><span>{team.name}</span><ChevronRight size={14}/><span>{getUser(team.lead_id).name}</span><ChevronRight size={14}/><b>{u.name}</b></div><div className="profile-hero"><div className="avatar xlarge">{u.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h2>{u.name}</h2><p>{u.title}</p><div className="relationship"><span>Team <b>{team.name}</b></span><span>Team Lead <b>{getUser(team.lead_id).name}</b></span><span>Current <b>09:00 AM – 05:00 PM</b></span><span>Previous <b>01:00 PM – 09:00 PM</b></span></div></div></div>{error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}<div className="split"><div className="panel"><div className="panel-head"><div><h2>Current shift activity</h2><p>Only events inside 09:00 AM – 05:00 PM are eligible.</p></div><span className="source-pill">{current.length} source events</span></div><Timeline events={current}/></div><div className="panel"><div className="panel-head"><div><h2>Last completed shift</h2><p>01:00 PM – 09:00 PM · previous day</p></div></div><PreviousShift userId={userId}/></div></div>{handover&&<HandoverPreview handover={handover} setModal={setModal}/>}</>}
function Timeline({events}:{events:Event[]}){if(!events.length)return <div className="empty">Nothing to report in this shift window.</div>;return <div className="timeline">{events.map(e=><div className="timeline-item" key={e.id}><div className="time">{fmt(e.timestamp)}</div><div className={`timeline-dot ${e.status}`}/><div className="timeline-body"><div className="event-top"><b>{e.record_id}</b><span className={`badge ${badgeClass(e.status)}`}>{e.status.replace('_',' ')}</span></div><p>{e.summary}</p><small>Source: {e.source} / {e.record_id}</small></div></div>)}</div>}
function PreviousShift({userId}:{userId:string}){const [events,setEvents]=useState<Event[]>([]);useEffect(()=>{fetch(`${API}/events?workerId=${userId}&start=${encodeURIComponent(previousStart)}&end=${encodeURIComponent(previousEnd)}`).then(r=>r.json()).then(setEvents).catch(()=>{})},[userId]);const groups=useMemo(()=>{const map=new Map<string,Event>();events.forEach(e=>map.set(e.source+'|'+e.record_id,e));return [...map.values()].sort((a,b)=>a.timestamp.localeCompare(b.timestamp))},[events]);return <div className="previous-list">{groups.map(e=><div className="previous-item" key={e.id}><span className={`icon-status ${e.status}`}><StatusIcon status={e.status}/></span><div><b>{e.record_id} — {e.summary}</b><span>{fmt(e.timestamp)} · {e.source}</span></div></div>)}{!groups.length&&<div className="empty">Nothing to report</div>}</div>}
function StatusIcon({status}:{status:Status}){if(status==='completed')return <CheckCircle2 size={15}/>;if(status==='blocked'||status==='escalated')return <AlertTriangle size={15}/>;return <CircleDot size={15}/>}
function badgeClass(s:string){return s==='completed'||s==='resolved'?'good':s==='blocked'||s==='escalated'?'bad':s==='watch'?'warn':'info'}

function HandoverPreview({handover,setModal}:{handover:Handover,setModal:(m:'summary'|'full'|null)=>void}){return <div className="handover-preview"><div className="panel-head"><div><span className="eyebrow">NEXT SHIFT</span><h2>Handover ready</h2><p>{handover.eventCount} in-window events · {handover.duplicateUpdatesCollapsed} duplicate updates collapsed</p></div><button className="primary" onClick={()=>setModal('summary')}>Open quick summary <ArrowRight size={15}/></button></div><div className="four-grid"><SummaryCard title="Completed" icon={<CheckCircle2/>} items={handover.completed}/><SummaryCard title="Still pending" icon={<CircleDot/>} items={handover.inProgress}/><SummaryCard title="Blockers / escalations" icon={<AlertTriangle/>} items={handover.blockers}/><SummaryCard title="Watch-list" icon={<Bell/>} items={handover.watch}/></div><div className="priority-strip"><div><b>Start with these</b><span>Derived from unresolved source records only.</span></div><div className="priority-row">{handover.priorities.slice(0,3).map((x,i)=><span key={x.record_id}><b>{i+1}</b>{x.record_id} — {x.summary}</span>)}</div><button className="secondary" onClick={()=>setModal('full')}>View full handover</button></div></div>}
function SummaryCard({title,icon,items}:{title:string,icon:React.ReactNode,items:HandoverItem[]}){return <div className="summary-card"><div className="summary-head">{icon}<b>{title}</b><span>{items.length}</span></div>{items.slice(0,3).map(x=><div className="summary-item" key={x.record_id}><b>{x.record_id}</b><span>{x.summary}</span></div>)}{!items.length&&<div className="empty small">Nothing to report</div>}</div>}
function HandoverPage({handover,loading,error,onGenerate,setModal}:{handover:Handover|null,loading:boolean,error:string,onGenerate:()=>void,setModal:(m:'summary'|'full'|null)=>void}){return <><PageTitle title="Shift handover" subtitle="Deterministic output from the selected shift window" action={<button className="primary" onClick={onGenerate}><Sparkles size={15}/>{loading?'Generating…':'Regenerate'}</button>}/>{error&&<div className="error"><AlertTriangle size={17}/>{error}</div>}{handover?<><div className="handover-meta"><div><span>Worker</span><b>{handover.worker.name}</b></div><div><span>Team</span><b>{handover.team.name}</b></div><div><span>Team Lead</span><b>{handover.lead.name}</b></div><div><span>Shift</span><b>09:00 AM – 05:00 PM</b></div><div><span>Events used</span><b>{handover.eventCount}</b></div></div><div className="quick-actions"><button className="primary" onClick={()=>setModal('summary')}>Open simple summary</button><button className="secondary" onClick={()=>setModal('full')}>View detailed handover</button></div><HandoverDetail handover={handover}/></>:<div className="empty-state"><FileText size={32}/><h2>Generate a grounded handover</h2><p>The system will filter events to the 09:00–17:00 shift, deduplicate updates, classify final states, and attach traceability.</p><button className="primary" onClick={onGenerate}>Generate handover</button></div>}</>}
function HandoverDetail({handover}:{handover:Handover}){const sections=[['COMPLETED',handover.completed,'good'],['IN PROGRESS',handover.inProgress,'info'],['BLOCKERS / ESCALATIONS',handover.blockers,'bad'],['WATCH-LIST',handover.watch,'warn']] as const;return <div className="detail-card"><div className="detail-title"><div><span className="eyebrow">SHIFT HANDOVER NOTE</span><h2>{handover.worker.name} · {handover.team.name}</h2></div><span className="source-pill">Generated {dateTime(new Date().toISOString())}</span></div>{sections.map(([title,items,cl])=><section className="detail-section" key={title}><div className="detail-section-head"><h3>{title}</h3><span>{items.length}</span></div>{items.length?items.map(item=><div className="handover-line" key={item.source+item.record_id}><div className={`line-icon ${cl}`}><StatusIcon status={cl==='good'?'completed':cl==='bad'?'blocked':cl==='warn'?'watch':'in_progress'}/></div><div className="line-main"><b>{item.record_id} — {item.summary}</b><div className="trace"><span>Source: <b>{item.source}</b></span><span>Record ID: <b>{item.record_id}</b></span><span>Timestamp: <b>{dateTime(item.timestamp)}</b></span><span>Final status: <b>{item.finalStatus}</b></span></div>{item.updates.length>1&&<small>Collapsed updates: {item.updates.join(' → ')}</small>}</div></div>):<div className="empty">Nothing to report</div>}</section>)}<section className="priority-section"><h3>Next-shift priorities</h3>{handover.priorities.length?handover.priorities.map((x,i)=><div className="priority-detail" key={x.record_id}><b>{i+1}</b><span><strong>{x.record_id}</strong> — {x.summary}<small>Source: {x.source} · {dateTime(x.timestamp)}</small></span></div>):<div className="empty">Nothing to report</div>}</section><div className="grounding"><ShieldAlert size={17}/><div><b>Grounding check</b><span>Every item above maps to a source + record ID + timestamp. No LLM is required for generation.</span></div></div></div>}
function HandoverModal({handover,mode,close}:{handover:Handover,mode:'summary'|'full',close:()=>void}){return <div className="modal-backdrop" onClick={close}><div className={mode==='summary'?'modal quick-modal':'modal full-modal'} onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">NEXT SHIFT HANDOVER</span><h2>{mode==='summary'?'Quick shift summary':'Detailed handover'}</h2><p>{handover.worker.name} · {handover.team.name} · 09:00 AM – 05:00 PM</p></div><button className="icon-btn" onClick={close}><X/></button></div>{mode==='summary'?<><div className="step-cards"><div><span>01</span><h3>Shift completed</h3><SummaryLines items={handover.completed}/><button onClick={()=>{}}>Continue <ArrowRight size={14}/></button></div><div><span>02</span><h3>Still pending</h3><SummaryLines items={handover.inProgress}/><button onClick={()=>{}}>Continue <ArrowRight size={14}/></button></div><div><span>03</span><h3>Blockers / escalations</h3><SummaryLines items={handover.blockers}/><button onClick={()=>{}}>Continue <ArrowRight size={14}/></button></div><div><span>04</span><h3>Start with these</h3><SummaryLines items={handover.priorities}/><button className="primary" onClick={()=>window.dispatchEvent(new CustomEvent('open-full'))}>View full handover <ArrowRight size={14}/></button></div></div><div className="modal-footer"><button className="secondary" onClick={close}>Close</button><button className="primary" onClick={()=>exportPdf(handover)}>Export handover PDF <Download size={15}/></button></div></>:<><HandoverDetail handover={handover}/><div className="modal-footer"><button className="secondary" onClick={close}>Close</button><button className="primary" onClick={()=>exportPdf(handover)}>Export handover PDF <Download size={15}/></button></div></>}</div></div>}
function SummaryLines({items}:{items:HandoverItem[]}){return <div className="summary-lines">{items.length?items.slice(0,4).map(x=><div key={x.record_id}><b>{x.record_id}</b><span>{x.summary}</span></div>):<em>Nothing to report</em>}</div>}
function Reports(){return <><PageTitle title="Reports" subtitle="Demo reporting surface"/><div className="report-grid"><div className="report-card"><BarChart3/><b>Handover coverage</b><strong>100%</strong><span>All seeded workers have a deterministic handover path.</span></div><div className="report-card"><ClipboardCheck/><b>Traceability</b><strong>100%</strong><span>Generated items carry source, record ID and timestamp.</span></div><div className="report-card"><ShieldAlert/><b>Duplicate control</b><strong>Active</strong><span>Updates collapse by source + record ID.</span></div></div></>}
function exportPdf(h:Handover){try{const doc=new jsPDF();let y=18;doc.setFontSize(20);doc.text('SHIFT HANDOVER NOTE',14,y);y+=9;doc.setFontSize(10);doc.text(`${h.worker.name} · ${h.team.name} · Team Lead ${h.lead.name}`,14,y);y+=6;doc.text('Shift: 09:00 AM – 05:00 PM (IST)',14,y);y+=9;const sections:[string,HandoverItem[]][]=[['COMPLETED',h.completed],['IN PROGRESS',h.inProgress],['BLOCKERS / ESCALATIONS',h.blockers],['WATCH-LIST',h.watch]];for(const [title,items] of sections){doc.setFontSize(13);doc.text(title,14,y);y+=6;if(!items.length){doc.setFontSize(10);doc.text('Nothing to report',18,y);y+=7}else for(const it of items){doc.setFontSize(10);const text=`${it.record_id} — ${it.summary}`;const lines=doc.splitTextToSize(text,175);if(y>270){doc.addPage();y=18}doc.text(lines,18,y);y+=5*lines.length;doc.setFontSize(8);doc.text(`Source: ${it.source} | Record ID: ${it.record_id} | Timestamp: ${dateTime(it.timestamp)} | Final: ${it.finalStatus}`,18,y);y+=7;if(it.updates.length>1){doc.text(`Updates collapsed: ${it.updates.join(' → ')}`,18,y);y+=6}}y+=3}doc.setFontSize(13);doc.text('NEXT-SHIFT PRIORITIES',14,y);y+=7;h.priorities.forEach((it,i)=>{if(y>270){doc.addPage();y=18}doc.setFontSize(10);doc.text(`${i+1}. ${it.record_id} — ${it.summary}`,18,y);y+=6;doc.setFontSize(8);doc.text(`Source: ${it.source} | Timestamp: ${dateTime(it.timestamp)}`,18,y);y+=7});doc.save(`shift-handover-${h.worker.name.replace(/\s+/g,'-').toLowerCase()}.pdf`)}catch(e){alert('PDF generation failed. Please try again.')}}

window.addEventListener('open-full',()=>{});
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
